### ISSUE TITLE
尝试每轮保存测试结果时出现了错误

### ISSUE THREAD

**Issue by wang1528186571** [WhoTHU/Adversarial_Texture#10]
```
precision: type=<class 'list'>, shape=(4810,)
recall: type=<class 'list'>, shape=(4810,)
avg: type=<class 'numpy.float64'>, shape=()
confs: type=<class 'numpy.ndarray'>, shape=(37, 130)
thetas: type=<class 'numpy.ndarray'>, shape=(37,)
  0%|                                                                                                                                                                                                    | 0/600 [07:07<?, ?it/s]
Traceback (most recent call last):
  File "/home/wang/Desktop/wjl-project-1/Adversarial_camou_pc/train.py", line 825, in <module>
    trainer.train()
  File "/home/wang/Desktop/wjl-project-1/Adversarial_camou_pc/train.py", line 636, in train
    np.savez(path, thetas=thetas, info=info)
  File "<__array_function__ internals>", line 200, in savez
  File "/home/wang/Anaconda3/envs/camou/lib/python3.8/site-packages/numpy/lib/npyio.py", line 615, in savez
    _savez(file, args, kwds, False)
  File "/home/wang/Anaconda3/envs/camou/lib/python3.8/site-packages/numpy/lib/npyio.py", line 716, in _savez
    val = np.asanyarray(val)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```

你好，在咱们的代码中我想要1轮测试一次这个效果并保存test_results_tps_iou01_person，但在实际测试中，会出现上面的错误，是训练过程太短导致的吗？
如下代码：
我尝试每一轮都保存这个测试结果，但会报上面的错误
```
                if (epoch + 1) % 1 == 0:
                self.update_mesh(type='determinate')
                for iou_thresh in [0.01, 0.1, 0.3, 0.5]:
```

**Comment by WhoTHU** [comment]
您好，请问报错的是本仓库代码中的哪一行？

**Comment by wang1528186571** [comment]
> 您好，请问报错的是本仓库代码中的哪一行？

很抱歉，应该是迷彩camou中的代码中 我在那个里面的issue给您提供出错代码吧
